name: cifar100_wrn_bl

dataset:
  # Training datasets
  labeled: cifar100 # choices: [cifar10, cifar100]
  unlabeled: none # choices: [tin, none]

  # Datasets to validate on after every epoch
  # choices: [cifar10, texture, svhn, cifar100, tin, lsun, places365]
  test_ood: [tin]

  labeled_batch_size: 128
  unlabeled_batch_size: 256
  test_batch_size: 200

network: networks.WideResNet
network_args:
  depth: 40
  widen_factor: 4
  dropRate: 0.0

trainer: trainers.BaseTrainer
trainer_args:

optim_args:
  epochs: 100
  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 0.0005
