name: scood
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.8.1
  - torchvision=0.9.1
  - cudatoolkit=10.1
  - faiss-gpu=1.7.1
  - scikit-learn=0.24.2
  - pip
  - pip:
    - pyyaml