# Dataset settings
dataset_type: scood # choices: [scood, ddood]
id_dataset: cifar100 # choices: [cifar10, cifar100]
ood_datasets: [cifar10, texture, svhn, tin, lsun, places365]
# Whether to evaluate each dataset individually, or combine them all altogether
eval_method: each # choices: [each, full]
batch_size: 200
# Type of interpolation when resizing images
interpolation: bilinear # choices: [nearest, bilinear]

network: networks.WideResNet
network_args:
  depth: 40
  widen_factor: 4
  dropRate: 0.0

# Post-processing method
postprocess: postprocessors.BasePostprocessor
postprocess_args:
  # temperature: 1000 # for ebo and odin
  # noise: 0.0014 # for odin
